server:
  port: 10001
#rdb:
#  type: 'postgres'
#  host: '192.168.0.24'
#  port: 5433
#  username: 'postgres'
#  password: 'qlalfqjsghekd'
#  database: 'postgres'
#  autoLoadEntities: true
#  synchronize: true
#  schema: 'example'
#  logging: true
#  dropSchema: true
#spring:
#  r2dbc:
#    url: r2dbc:postgresql://192.168.0.24:5433/postgres
#    username: postgres
#    password: qlalfqjsghekd
#    name: postgres

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: r2dbc:postgresql://192.168.0.24:5433/postgres
#    username: postgres
#    password: qlalfqjsghekd
discord:
  token: ENC(34SoVsUK8YTwl7CDOap+n40F0d5MbiIf9Rn1bY2S4H9OlfSPtaw9SXMB6K7dR68RexFny+BKM6g4n4267Y98BODNwZLjp8n3ZHE1iWvYcWkly6OuIN+a)
  webhook:
    id: ENC(Zk1uDKCWwQ9LYlZdQVwX4SAghiRncGLB+4aCxnv8IrWJscWa2Vq/IBaxu7Li3A==)
    token: ENC(CcPhHbKI8y8avavGVrA+qpbJglG4+2q8eHS9zUs5l12nNWJ+5wkvli9PshFoRBRw30Bw6IxdmBku8zyv1+sESelcw8inD0gkjt+RJjKOLOQ1Mk4G7Xe000CJhb3cLFTo)
logging:
  file:
    path: ./
